### ISSUE TITLE
__unocss_ready/1639148123556 are not found.

### ISSUE THREAD

**Issue by chuoke** [antfu/unocss#254]
I use Unocss with Inertiajs and Vite in Laravel. They are running on two different hosts. And I got errors as follows:
```
http://localhost/__unocss_ready/1639148123556 
404 Not Found
```
This is the domain name of the master site (Laravel with Inertia), but Vite is on `http://localhost:3000`. 

And I found some code in Unocss
```
const READY_CALLBACK_DEFAULT = "/__unocss_ready";
```
I guess that's why it's wrong. Didn't find a way to customize it. Any help?

Btw, That doesn't seem to affect Unocss's work.

**Comment by RAGGA-TIME** [comment]
How to resolve？

**Comment by buhrmi** [comment]
I think the problem is that https://github.com/antfu/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L126 should make a request to vite dev server, but instead its going to the main app server

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by buhrmi** [comment]
This happens only if the dev server (`./bin/vite dev`) is running. FWIW, I'm also using Inertiajs, but with Rails (instead of Laraval) using [ViteRuby](https://github.com/ElMassimo/vite_ruby)

**Comment by buhrmi** [comment]
When using ViteRuby's, the dev server listens under `/vite-dev`, so [this condition](https://github.com/antfu/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L74) can never be true. Maybe @ElMassimo has an idea what to do here 🤔

**Comment by ElMassimo** [comment]
@buhrmi The unocss middleware check that you linked should take the Vite base under account (which should fix this issue).

In the meantime, in Vite Ruby you can specify [`"publicOutputDir": ""`](https://github.com/ElMassimo/vite_ruby/pull/164) in development (must be in [`vite_ruby@3.0.6`](https://github.com/ElMassimo/vite_ruby/compare/vite_ruby@3.0.5...vite_ruby@3.0.6)), which will use an empty base.

**Comment by userquin** [comment]
I'll fix it: we need to add the `base` to the generated `fetch` code.

**Comment by chuoke** [comment]
Thank you @userquin.

Do I only need to update this version?  Do I need to modify or add some configurations?

**Comment by userquin** [comment]
@chuoke just update , maybe you need to uninstall and install again the dependencies...

**Comment by chuoke** [comment]
@userquin  It seems still not working, But it's closer than it was.

And I found this code:
```
return `${code}\nawait fetch("${base}${READY_CALLBACK_DEFAULT}/${lastServed}")`
```

I wonder, can change it directly to like this:
```
return `${code}\nawait fetch("${vite_host}${base}${READY_CALLBACK_DEFAULT}/${lastServed}")`
```
The vite_host is resolved from vite config like the base.

This can be perfect with my problem.

**Comment by userquin** [comment]
@chuoke are you using `server.host` and `server.port` in your project? can you share your Vite config file?

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/147939027-1d9baa9f-5216-456c-bdd5-a9e2a3cc1c50.png)

**Comment by userquin** [comment]
The Vite configuration (it is an sveltekit project, just see the `server` option):

![imagen](https://user-images.githubusercontent.com/6311119/147939100-df4439f2-f668-44a5-8e13-ad59d9800429.png)

**Comment by userquin** [comment]
@chuoke  Upps, you're connecting 2 servers, sorry man, maybe we can include some resolver for the base url, I'll take a look...

**Comment by chuoke** [comment]
Yes, I use them.

```
"server": {
        "preTransformRequests": true,
        "host": "192.168.56.1",
        "https": false,
        "port": 3000,
        "origin": "http://192.168.56.1:3000",
        "hmr": {
            "host": "192.168.56.1",
            "port": 3000
        },
    },
```
This is the server part of the runtime configuration that I printed out because part of the configuration is dynamic.

**Comment by userquin** [comment]
With previous configuration  the inspector should work at `http://192.168.56.1:3000/__unocss/` (if you have a `base` should be http://192.168.56.1:3000/<base>/__unocss/)

If you have another server in front of previous one, you should proxy all request from `http://<another_host>:<another_port>/__unocss/*` to `http://192.168.56.1:3000/__unocss/*`. If the front end server is also a vite project it can be done with `server.proxy`, if you're using another server you should check the docs to do it.

**Comment by userquin** [comment]
Sorry again, can you explain your configuration?

**Comment by chuoke** [comment]
I run Vite with Laravel using [Inertial Vue3](https://inertiajs.com) and [Laravel-vite](https://laravel-vite.innocenzi.dev/), which did a little bit of processing. And Vite and Laravel running on a different server.

I use a domain for the Laravel app, such as http://my-app.test, which is in the foreground.
Vite just on http://192.168.56.1:3000/build, actually.

The Laravel app is responsible for data processing and by Inertial to tell Vue which component should be rendered. So Vite is like a backroom supporter.

**Comment by userquin** [comment]
@chuoke can you provide a minimal repro (gh or starblizt) so I can check it?

**Comment by chuoke** [comment]
Can you use PHP? I have a reproduction: [https://github.com/chuoke/laravel-with-inertail-and-vite-error-reproduction](/chuoke/laravel-with-inertail-and-vite-error-reproduction) ,
After you run all servers, visit Laravel server, you'll see  404 errors like `http://127.0.0.1:8000/__unocss_ready/1641225308035` in the console.

**Comment by userquin** [comment]
@chuoke I have installed PHP 8.11 and composer but starting the PHP server I have 2 problems: port 8000 cannot be used and once started on 8081 (PHP change the port automatically) then I have an error about encryption not configured.

Can we move here https://github.com/antfu/unocss/discussions/387?

**Comment by chuoke** [comment]
🎉  Now, It works. Thank you.

BTW, it released in [v0.24.0](https://github.com/unocss/unocss/releases/tag/v0.24.0).

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
