### ISSUE TITLE
Supporting pug template preprocessor

### ISSUE THREAD

**Issue by tjk** [antfu/unocss#58]
Is the right approach to just make a pug extractor or should the default extractor just be pipelined correctly after the template gets preprocessed?

**Comment by tjk** [comment]
For now, it looks like just adding a `.` to `extractorSplit` might be good enough --

```
// export const extractorSplit: Extractor = code => new Set(code.split(/[\s'"`;>=]+/g).filter(isValidSelector))
extractors: [
  code => new Set(code.split(/[.\s'"`;>=]+/g).filter(isValidSelector))
],
```

**Comment by davay42** [comment]
I'm having trouble with making unocss wotk with PUG too. Where should we put it @tjk ? May be it should be fixed on the lib level @antfu ?

**Comment by davay42** [comment]
Oh, found the  https://github.com/antfu/unocss/tree/main/packages/extractor-pug .... 😅

**Comment by davay42** [comment]
But still I don't get hot reload with updated styles. Only restarting the dev server recreates newly added styles to a component...

**Comment by tjk** [comment]
Please follow along in https://github.com/antfu/unocss/issues/66. `@unocss/extrator-pug` still not handling vue sfc with pug template `@vitejs/plugin-vue` hot reloads correctly because the regex looks for `template lang="pug"` but `@vitejs/plugin-vue` emits virtual module update which only includes the actual template contents (so that needle is not found). Would love to contribute a patch but I'm not sure the best way forward.
